[workspace]
members = ["crates/*"]
# example is built for wasm and we can't have multiple targets in the same workspace
exclude = ["examples/example-source"]
resolver = "3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true
