[package]
name = "example_source"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt = "s"
strip = "debuginfo"
lto = true

[dependencies]
aidoku_imports = { path = "../aidoku_imports" }