[package]
name = "aidoku_proc_macros"
version = "0.2.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.36"
quote = "1.0.17"
syn = { version = "1.0.90", features = ["full"] }
