name: CI checks
on:
  pull_request:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - run: sudo apt install pkg-config libfreetype6-dev libfontconfig1-dev
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --workspace --no-deps --lib
      - name: Uploading build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: target/doc
          if-no-files-found: ignore
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: target/doc
          git-config-name: GitHub Actions
          git-config-email: github-actions[bot]@users.noreply.github.com
          commit-message: Update documentation
          single-commit: true
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - run: sudo apt install pkg-config libfreetype6-dev libfontconfig1-dev
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
