name: CI checks
on:
  pull_request:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            target: wasm32-unknown-unknown
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps
      - name: Uploading build artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: target/wasm32-unknown-unknown/doc
          if-no-files-found: ignore
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: target/wasm32-unknown-unknown/doc
          git-config-name: GitHub Actions
          git-config-email: github-actions[bot]@users.noreply.github.com
          commit-message: Update documentation
          single-commit: true
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
            target: wasm32-unknown-unknown
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  test-breaking-changes: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: aidoku-rs
      - uses: actions/checkout@v3
        with:
          path: aidoku-community-sources
          repository: Skittyblock/aidoku-community-sources
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown
      -
        name: Install build dependencies
        run: brew install beerpiss/tap/aidoku-cli
      - name: Applying Cargo dependency patch
        run: |
          for file in aidoku-community-sources/src/rust/*/Cargo.toml; do
            printf "\n[patch.\"https://github.com/Aidoku/aidoku-rs/\"]\naidoku = { path = \"../../../../aidoku-rs/crates/lib\" }\n" >> $file
            printf "\n[patch.\"https://github.com/Aidoku/aidoku-rs\"]\naidoku = { path = \"../../../../aidoku-rs/crates/lib\" }\n" >> $file  
          done
      - name: Building sources
        run: |
          for src in aidoku-community-sources/src/rust/*; do
          (
            cd "$src"
            cargo update
            ./build.sh -a
          )
          done
      - name: Building source list
        run: |
          aidoku build ./**/*.aix
      - name: Uploading packages as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: packages
          path: public/sources/*.aix
          if-no-files-found: ignore

